#!/bin/sh

super + {_,shift +}Return
	{st,bspc node -s biggest.local}

super + d
	dmenu_run

super + Escape
	pkill -USR1 -x sxhkd

super + shift + {q,r}
	bspc {quit,wm -r}

super + shift + c
	bspc node -c

super + {_,shift + }{1-9}
	bspc {desktop -f,node -d} '^{1-9}'
